### ISSUE TITLE
reorganise code 

### ISSUE THREAD

**Issue by katrinleinweber** [freifunk/vis.api.freifunk.net#14]
Currently, it's organised by topic, but that doesn't seem to be very elegant. Consider alternative organisations of the `.R` files, like by:
- data source [current](https://api.freifunk.net/data/ffSummarizedDir.json) JSON & [history](https://api.freifunk.net/data/history/)
- code type (functions, processing steps, plotting, etc.)
- or even [create a package](https://stackoverflow.com/questions/1266279/how-to-organize-large-r-programs)

**Comment by katrinleinweber** [comment]
I never got around to doing this. I'm sorry.

**Comment by extua** [comment]
Closing this as part of issue cleanup
