### ISSUE TITLE
Set up MongoDB on a remote server

### ISSUE THREAD

**Issue by extua** [freifunk/vis.api.freifunk.net#32]
Kind of a general issue, MongoDB won't work on my laptop, due to [lack of AVX support](https://www.mongodb.com/community/forums/t/one-more-time-about-mongo-5-cpu-requirements/168858) on my very primitive laptop CPU.

Thankfully most of the work has already been done to be able to deploy it anywhere.

**Comment by extua** [comment]
Tracking this to document later, this is for a server running Debian Bookworm:

- Install docker [instructions here](https://docs.docker.com/engine/install/debian/#install-using-the-repository) and [post-install permissions](https://docs.docker.com/engine/install/linux-postinstall/).
- Clone the respository `git clone git@github.com:freifunk/vis.api.freifunk.net.git`
- `docker compose up -d`
- Install MongoDB to be able to query the database with mongosh [tutorial](https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-debian/).
- Add test files to `api.freifunk.net/data/history/` with wget `wget -A json -m -E -k -K -np -v https://api.freifunk.net/data/history/` (wait a while as this takes some time).

Todo:
- Build json_adder (?) or download release?
- Run json_adder to add the files to the database.
- Test that the files are in the database

**Comment by mtippmann** [comment]
@extua maybe @andibraeu can setup some server ressources for you - just for testing it looks like mongodb has a cloud office with a free-tier up to 5gb of data here: https://www.mongodb.com/pricing

**Comment by extua** [comment]
@mtippmann I set up a server with Hetzner this morning, which is not too expensive and works for the moment. I will need a 'Freifunk' server from @andibraeu when it comes to deploy the finished process. In the meantime thanks for the tip about the free cloud tier! I'll see about setting that up later.

**Comment by extua** [comment]
@mtippmann here's a connection string for MongoDB Atlas

```
mongodb+srv://databaseReader:freifunkfreifunk@freifunktest.zsfzlav.mongodb.net/
```
